### ISSUE TITLE
Transcriptome dataset as input data 

### ISSUE THREAD

**Issue by azam17** [lmcai/PhyloHerb#1]
Hi, can this pipeline be used on transcriptome dataset?

**Comment by lmcai** [comment]
Of course. Transcriptomes can be used as either input or output for the pipeline. Do you want to get organelle genes from transcriptomes?

**Comment by azam17** [comment]
Yes. plastid genes

**Comment by azam17** [comment]
Hi, i encountered an issue when using the tool. i am sure that i have include the input directory in the command but it seems that the script printed out an error stating the input file is not found. below is the command line output:

`
python phyloherb.py -m ortho -i ~/taylors/03_INPUT/ -o ~/taylors/04_OUTPUT/ -l 120
 __                 __        ___  __   __  
|__) |__| \ / |    /  \ |__| |__  |__) |__) 
|    |  |  |  |___ \__/ |  | |___ |  \ |__) 

############################################################
PhyloHerb v1.1.1
A bioinformatic pipeline for herbariomics based biodiversity research

Using all 7 species found in /home/amaliamohdhashim/taylors/03_INPUT/: trinity_Aul, trinity_Aac, trinity_Atr, trinity_Ael, trinity_Ate, trinity_Acu, trinity_Asm
Using length cutoff 120 bp for BLAST result filtering
Using build-in plastid gene set
processing species trinity_Aul.assembly.fas


Building a new DB, current time: 03/07/2023 12:02:31
New DB name:   /home/amaliamohdhashim/installation/PhyloHerb/trinity_Aul.assembly.fas
New DB title:  /home/amaliamohdhashim/taylors/03_INPUT//trinity_Aul.assembly.fas
Sequence type: Nucleotide
BLAST Database error: No alias or index file found for nucleotide database [trinity_Aul.assembly.fas] in search path [/home/amaliamohdhashim/installation/PhyloHerb::]
Deleted existing Nucleotide BLAST database named /home/amaliamohdhashim/installation/PhyloHerb/trinity_Aul.assembly.fas
Keep MBits: T
Maximum file size: 3000000000B
############################################################
#ERROR:Input files not found!
`

**Comment by lmcai** [comment]
It looks like BLAST is complaining. Can you type in the following command to see if it can build the reference database?
makeblastdb -in /home/amaliamohdhashim/installation/PhyloHerb/trinity_Aul.assembly.fas -dbtype nucl -out trinity_Aul.assembly.fas

**Comment by azam17** [comment]
yup, it can. 


makeblastdb -in /home/amaliamohdhashim/installation/PhyloHerb/trinity_Aul.assembly.fas -dbtype nucl -out trinity_Aul.assembly.fas


Building a new DB, current time: 03/08/2023 12:37:35
New DB name:   /home/amaliamohdhashim/installation/PhyloHerb/trinity_Aul.assembly.fas
New DB title:  /home/amaliamohdhashim/installation/PhyloHerb/trinity_Aul.assembly.fas
Sequence type: Nucleotide
Deleted existing Nucleotide BLAST database named /home/amaliamohdhashim/installation/PhyloHerb/trinity_Aul.assembly.fas
Keep MBits: T
Maximum file size: 3000000000B
Adding sequences from FASTA; added 291614 sequences in 7.12393 seconds

**Comment by lmcai** [comment]
I cannot repeat your error on my own computer under similar settings. Can you use the attached phyloherb_debug.py to rerun the analysis? This version will screen output all BLAST commands so I can see what's going on inside. Please let me know if any database files *.nhr, *.nin, *.nsq and blast ourputs *.blast.out are being generated. You will need to change the downloaded file name from phyloherb_debug.txt to phyloherb_debug.py because GitHub does not allow such a file suffix for attachment.
[phyloherb_debug.txt](https://github.com/lmcai/PhyloHerb/files/10917417/phyloherb_debug.txt)

**Comment by azam17** [comment]
for some reason, i managed to completely run the phyloherb_debug.py but not the default phyloherb.py

this is the final output of the phyloherb_debug.py :

__) |__| \ / |    /  \ |__| |__  |__) |__) 
|    |  |  |  |___ \__/ |  | |___ |  \ |__) 


############################################################
PhyloHerb v1.1.1
A bioinformatic pipeline for herbariomics based biodiversity research

Using all 7 species found in /home/amaliamohdhashim/taylors/03_INPUT/: trinity_Aul, trinity_Aac, trinity_Atr, trinity_Ael, trinity_Ate, trinity_Acu, trinity_Asm
Using length cutoff 60 bp for BLAST result filtering
Using build-in plastid gene set
processing species trinity_Aul.assembly.fas
makeblastdb -in /home/amaliamohdhashim/taylors/03_INPUT//trinity_Aul.assembly.fas -dbtype nucl -out trinity_Aul.assembly.fas


Building a new DB, current time: 03/08/2023 14:23:33
New DB name:   /home/amaliamohdhashim/installation/PhyloHerb/trinity_Aul.assembly.fas
New DB title:  /home/amaliamohdhashim/taylors/03_INPUT//trinity_Aul.assembly.fas
Sequence type: Nucleotide
Deleted existing Nucleotide BLAST database named /home/amaliamohdhashim/installation/PhyloHerb/trinity_Aul.assembly.fas
Keep MBits: T
Maximum file size: 3000000000B
Adding sequences from FASTA; added 291614 sequences in 7.32742 seconds.


blastn -task dc-megablast -db trinity_Aul.assembly.fas -query /home/amaliamohdhashim/installation/PhyloHerb/database/plastid_reference.fas -num_threads 1 -outfmt 6 -evalue 1e-20 -out trinity_Aul.assembly.fas.blast.out
processing species trinity_Aac.assembly.fas
makeblastdb -in /home/amaliamohdhashim/taylors/03_INPUT//trinity_Aac.assembly.fas -dbtype nucl -out trinity_Aac.assembly.fas


Building a new DB, current time: 03/08/2023 14:33:53
New DB name:   /home/amaliamohdhashim/installation/PhyloHerb/trinity_Aac.assembly.fas
New DB title:  /home/amaliamohdhashim/taylors/03_INPUT//trinity_Aac.assembly.fas
Sequence type: Nucleotide
Keep MBits: T
Maximum file size: 3000000000B
Adding sequences from FASTA; added 334155 sequences in 8.47006 seconds.


blastn -task dc-megablast -db trinity_Aac.assembly.fas -query /home/amaliamohdhashim/installation/PhyloHerb/database/plastid_reference.fas -num_threads 1 -outfmt 6 -evalue 1e-20 -out trinity_Aac.assembly.fas.blast.out
processing species trinity_Atr.assembly.fas
makeblastdb -in /home/amaliamohdhashim/taylors/03_INPUT//trinity_Atr.assembly.fas -dbtype nucl -out trinity_Atr.assembly.fas


Building a new DB, current time: 03/08/2023 14:45:43
New DB name:   /home/amaliamohdhashim/installation/PhyloHerb/trinity_Atr.assembly.fas
New DB title:  /home/amaliamohdhashim/taylors/03_INPUT//trinity_Atr.assembly.fas
Sequence type: Nucleotide
Keep MBits: T
Maximum file size: 3000000000B
Adding sequences from FASTA; added 204823 sequences in 5.42698 seconds.


blastn -task dc-megablast -db trinity_Atr.assembly.fas -query /home/amaliamohdhashim/installation/PhyloHerb/database/plastid_reference.fas -num_threads 1 -outfmt 6 -evalue 1e-20 -out trinity_Atr.assembly.fas.blast.out
processing species trinity_Ael.assembly.fas
makeblastdb -in /home/amaliamohdhashim/taylors/03_INPUT//trinity_Ael.assembly.fas -dbtype nucl -out trinity_Ael.assembly.fas


Building a new DB, current time: 03/08/2023 14:55:44
New DB name:   /home/amaliamohdhashim/installation/PhyloHerb/trinity_Ael.assembly.fas
New DB title:  /home/amaliamohdhashim/taylors/03_INPUT//trinity_Ael.assembly.fas
Sequence type: Nucleotide
Keep MBits: T
Maximum file size: 3000000000B
Adding sequences from FASTA; added 254993 sequences in 7.22234 seconds.


blastn -task dc-megablast -db trinity_Ael.assembly.fas -query /home/amaliamohdhashim/installation/PhyloHerb/database/plastid_reference.fas -num_threads 1 -outfmt 6 -evalue 1e-20 -out trinity_Ael.assembly.fas.blast.out
processing species trinity_Ate.assembly.fas
makeblastdb -in /home/amaliamohdhashim/taylors/03_INPUT//trinity_Ate.assembly.fas -dbtype nucl -out trinity_Ate.assembly.fas


Building a new DB, current time: 03/08/2023 15:06:34
New DB name:   /home/amaliamohdhashim/installation/PhyloHerb/trinity_Ate.assembly.fas
New DB title:  /home/amaliamohdhashim/taylors/03_INPUT//trinity_Ate.assembly.fas
Sequence type: Nucleotide
Keep MBits: T
Maximum file size: 3000000000B
Adding sequences from FASTA; added 230027 sequences in 6.29457 seconds.


blastn -task dc-megablast -db trinity_Ate.assembly.fas -query /home/amaliamohdhashim/installation/PhyloHerb/database/plastid_reference.fas -num_threads 1 -outfmt 6 -evalue 1e-20 -out trinity_Ate.assembly.fas.blast.out
processing species trinity_Acu.assembly.fas
makeblastdb -in /home/amaliamohdhashim/taylors/03_INPUT//trinity_Acu.assembly.fas -dbtype nucl -out trinity_Acu.assembly.fas


Building a new DB, current time: 03/08/2023 15:15:59
New DB name:   /home/amaliamohdhashim/installation/PhyloHerb/trinity_Acu.assembly.fas
New DB title:  /home/amaliamohdhashim/taylors/03_INPUT//trinity_Acu.assembly.fas
Sequence type: Nucleotide
Keep MBits: T
Maximum file size: 3000000000B
Adding sequences from FASTA; added 207325 sequences in 5.37984 seconds.


blastn -task dc-megablast -db trinity_Acu.assembly.fas -query /home/amaliamohdhashim/installation/PhyloHerb/database/plastid_reference.fas -num_threads 1 -outfmt 6 -evalue 1e-20 -out trinity_Acu.assembly.fas.blast.out
processing species trinity_Asm.assembly.fas
makeblastdb -in /home/amaliamohdhashim/taylors/03_INPUT//trinity_Asm.assembly.fas -dbtype nucl -out trinity_Asm.assembly.fas


Building a new DB, current time: 03/08/2023 15:25:25
New DB name:   /home/amaliamohdhashim/installation/PhyloHerb/trinity_Asm.assembly.fas
New DB title:  /home/amaliamohdhashim/taylors/03_INPUT//trinity_Asm.assembly.fas
Sequence type: Nucleotide
Keep MBits: T
Maximum file size: 3000000000B
Adding sequences from FASTA; added 204758 sequences in 5.30189 seconds.


blastn -task dc-megablast -db trinity_Asm.assembly.fas -query /home/amaliamohdhashim/installation/PhyloHerb/database/plastid_reference.fas -num_threads 1 -outfmt 6 -evalue 1e-20 -out trinity_Asm.assembly.fas.blast.out
Completed gene extraction for 7 species. Orthologous gene sequences are written to the output directory: /home/amaliamohdhashim/taylors/04_OUTPUT//.
